# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_auto_20160805_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
    ]
